import type { ThemePreset } from '../../../types';
import type { PresetTheme } from './types';

const violetBloomLightTheme: ThemePreset = {
  background: '#fdfdfd',
  foreground: '#000000',
  card: '#fdfdfd',
  cardForeground: '#000000',
  popover: '#fcfcfc',
  popoverForeground: '#000000',
  primary: '#7033ff',
  primaryForeground: '#ffffff',
  secondary: '#edf0f4',
  secondaryForeground: '#080808',
  muted: '#f5f5f5',
  mutedForeground: '#525252',
  accent: '#e2ebff',
  accentForeground: '#1e69dc',
  destructive: '#e54b4f',
  destructiveForeground: '#ffffff',
  border: '#e7e7ee',
  input: '#ebebeb',
  ring: '#000000',
  chart1: '#4ac885',
  chart2: '#7033ff',
  chart3: '#fd822b',
  chart4: '#3276e4',
  chart5: '#747474',
  sidebar: '#f5f8fb',
  sidebarForeground: '#000000',
  sidebarPrimary: '#000000',
  sidebarPrimaryForeground: '#ffffff',
  sidebarAccent: '#ebebeb',
  sidebarAccentForeground: '#000000',
  sidebarBorder: '#ebebeb',
  sidebarRing: '#000000',
  fontSans: 'Plus Jakarta Sans, sans-serif',
  fontSerif: 'Lora, serif',
  fontMono: 'IBM Plex Mono, monospace',
  radius: '1.4rem',
};

const violetBloomDarkTheme: ThemePreset = {
  background: '#1a1b1e',
  foreground: '#f0f0f0',
  card: '#222327',
  cardForeground: '#f0f0f0',
  popover: '#222327',
  popoverForeground: '#f0f0f0',
  primary: '#8c5cff',
  primaryForeground: '#ffffff',
  secondary: '#2a2c33',
  secondaryForeground: '#f0f0f0',
  muted: '#2a2c33',
  mutedForeground: '#a0a0a0',
  accent: '#1e293b',
  accentForeground: '#79c0ff',
  destructive: '#f87171',
  destructiveForeground: '#ffffff',
  border: '#33353a',
  input: '#33353a',
  ring: '#8c5cff',
  chart1: '#4ade80',
  chart2: '#8c5cff',
  chart3: '#fca5a5',
  chart4: '#5993f4',
  chart5: '#a0a0a0',
  sidebar: '#161618',
  sidebarForeground: '#f0f0f0',
  sidebarPrimary: '#8c5cff',
  sidebarPrimaryForeground: '#ffffff',
  sidebarAccent: '#2a2c33',
  sidebarAccentForeground: '#8c5cff',
  sidebarBorder: '#33353a',
  sidebarRing: '#8c5cff',
  fontSans: 'Plus Jakarta Sans, sans-serif',
  fontSerif: 'Lora, serif',
  fontMono: 'IBM Plex Mono, monospace',
};

const violetBloomTheme: PresetTheme = {
  light: violetBloomLightTheme,
  dark: violetBloomDarkTheme,
  name: 'Violet Bloom',
  id: 'violetBloom',
  source: 'tweakcn',
};

export default violetBloomTheme;
